package jobportal.service;

import jobportal.domain.resume.Education;
import jobportal.domain.resume.Resume;
import jobportal.domain.resume.Skill;
import jobportal.domain.resume.WorkExperience;

import java.nio.charset.StandardCharsets;

public class ResumeTemplateService {

    public enum Template {
        STANDARD_V1
    }

    public byte[] generate(Resume resume, Template template) {
        if (resume == null) return new byte[0];
        if (template == null) template = Template.STANDARD_V1;

        StringBuilder sb = new StringBuilder();

        switch (template) {
            case STANDARD_V1 -> {
                sb.append("====================================\n");
                sb.append("              RESUME                \n");
                sb.append("====================================\n");

                sb.append("Summary:\n");
                sb.append(nullToEmpty(resume.getSummary())).append("\n\n");

                sb.append("Skills:\n");
                if (resume.getSkills().isEmpty()) {
                    sb.append("- (none)\n");
                }
                for (Skill s : resume.getSkills()) {
                    sb.append("- ").append(s.getName()).append("\n");
                }

                sb.append("\nWork Experience:\n");
                if (resume.getWorkExperiences().isEmpty()) {
                    sb.append("- (none)\n");
                }
                for (WorkExperience we : resume.getWorkExperiences()) {
                    sb.append("- ")
                      .append(nullToEmpty(we.getPosition()))
                      .append(" @ ")
                      .append(nullToEmpty(we.getCompanyName()))
                      .append(" (")
                      .append(we.getStartDate())
                      .append(" to ")
                      .append(we.getEndDate())
                      .append(")\n");
                }

                sb.append("\nEducation:\n");
                if (resume.getEducation().isEmpty()) {
                    sb.append("- (none)\n");
                }
                for (Education ed : resume.getEducation()) {
                    sb.append("- ")
                      .append(nullToEmpty(ed.getDegree()))
                      .append(" in ")
                      .append(nullToEmpty(ed.getFieldOfStudy()))
                      .append(" @ ")
                      .append(nullToEmpty(ed.getInstitutionName()))
                      .append(" (Grad: ")
                      .append(ed.getGraduationDate())
                      .append(")\n");
                }

                sb.append("\n====================================\n");
                sb.append("Generated by Job Portal (Template-based)\n");
            }
        }

        return sb.toString().getBytes(StandardCharsets.UTF_8);
    }

    private String nullToEmpty(String s) {
        return s == null ? "" : s;
    }
}
